services:
  postgres:
    image: postgres:15
    container_name: prontomed-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: prontomed
    ports:
      - "5432:5432"